package com.trisys.rn.baseapp.utils

object Define {


    var URL_PLAYSTORE = "https://play.google.com/store/apps/details?id=com.vpnews24&hl=ta"
    var URL_FB = "https://www.facebook.com/vpnews24/"
    var URL_TWITTER = "https://twitter.com/vpnews24"
    var URL_TELEGRAM = "http://t.me/vpnews24"
    var URL_GOOGLE_PLUS = "https://plus.google.com/117903259919283813293"
    var DEVELOPER_KEY = "youtube_developer_key"


    val APP_LAST_OPEN_TIME = "app_last_open_time"
    val LIVE_TV_API_GETING_TIME = "live_tv_api_getting_time"
    val LIVE_TV_API_TIME_DIFF = "live_tv_api_time_diff"
    val LAUNCHER_IMAGE = "launcher_img"
    val APP_VERSION_CODE = "version"
    val APP_CHANGE_LOG = "change_log"
    val APP_STATUS = "app_status"
    val BASE_URL = "base_url"
    val SELECTED_LANGUAGE = "selected_language_vpnews24"
    //val SELECTED_LANGUAGE_CONFIG = "selected_language_config"
    val CATEGORY_CONFIG = "category_config_vpnews24"
    val LANGUAGE_LIST = "language_list"
    val NEWS_CONFIG = "news_config_vpnews24"
    val THEME_AUTO_CHANGE = "theme_auto_change"
    val THEME_NIGHT_MODE = "theme_night_mode"
    val DISABLE_IMAGES = "disable_images"
    val CLEAR_SHARE_IMAGE_DAYS = "clear_share_image_days"
    val HOME_SHOW_CRICKET = "home_show_cricket"
    val HOME_SHOW_DISTRICT = "home_show_district"
    val DISABLE_NOTIFICATION = "disable_notification"
    val ENABLE_GROUP_NOTIFICATION = "enable_group_notification"
    val ENABLE_BIG_NOTIFICATION = "enable_big_notification"
    val ICON_CATEGORY_SELECT_ALL = "icon_category_select_all"
    val NOTIFICATION_ON_OFF = "notification_on_off"
    val COME_FROM = "come_from"
    val NOTIFICTION_ID = "notification_id"
    val TAG_SHARE_NEWSITEM = "share_news_item"
    val SHARE_URL = "share_url"
    val PLAY_STORE = "play_store"
    val SHARE_APP_TEXT = "app_share_content"
    val CATEGORY_VIEW = "category_view"
    val WEBSITE = "website"
    val EMAIL = "email"
    val NOTIFICATION_DELETE_DATE = "notification_deletw_date"
    val FEEDBACK_ASK_AFTER = "feedback_ask_after"
    val FEEDBACK_ASK = "feedback_ask"
    val FEEDBACK_MSG = "feedback_msg"
    val FEEDBACK_title = "feedback_title"
    val FEEDBACK_ASK_FORCE = "feedback_ask_force"

    val PAPER_CONFIG_VERSION = "paper_config_version"
    val CATEGORY_CONFIG_VERSION = "category_config_version"
    val MESSAGE = "message"
    val MESSAGE_COUNT = "message_count"

    val BROADCAST_FAV_NEWS_SCREEN = "refresh_fav_news_screen"
    val LIVE_NEWS_DATA = "live_news_data"
    val LIVE_NEWS_VERSION = "live_tv_version"
    val CLEAR_NEWS_DAYS = "clear_news_days"
    val NEWS_TERMS_CONDITION = "news_terms_condition"

    val CRICKET_LIVE = "cricket_live"
    val HOME_OPTIONS = "home_option"
    val NEWS_VIEW_STYLE = "news_view_style"

    val CURRENT_FONT = "current_font"
    val CURRENT_FONT_SIZE = "current_font_size"
    val FONT_SIZE_HEADEING = "font_size_heading"
    val FONT_SIZE_DESCRIPTION = "font_size_description"
    val FONT_SIZE_DESCRIPTION_2 = "font_size_description_2"
    val FONT_SIZE_SECTION_HEADER = "font_size_section_header"
    val FONT_SIZE_SECTION_DESCRIPTION = "font_size_section_description"
    val FONT_SIZE_HOMESCREEN = "font_size_homescreen"
    val FONT_SIZE_DEFAULT = "font_size_default"

    val SCORE_UPDATE_ON_STATUSBAR = "score_update_on_statusbar"
    val SCORE_UPDATE_TIME_INTERVAL = "score_update_time_interval"
    val NEWS_SECTIONS_UPDATE_INTERVAL = "news_sections_update_interval"
    val CRICKET_VIEW = "cricket_view"
    val CRICKET_WEB_URL = "cricket_web_url"

    val NO_NEWS_IN_PAGE = "no_news_in_page"
    val SERVER_BASE_URL = "server_base_url"
    val SERVER_BASE_PATH = "server_base_path"
    val SERVER_NEWS_BASE_PATH = "server_news_base_path"
    val APP_VERSION_SPECIFIC = "app_version_specific"
    val MULTI_LANGUAGE = "multi_language"
}
